[project]
name = "accelerate-runner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "coverage==7.5.4",
    "pytest==8.2.2",
    "pytest-cov==5.0.0",
    "tdl-client-python==0.27.13",
]
